version: '3'
services:
  api:
    build: api/.
    ports:
     - 8080:80
    depends_on: 
     - db
  db:
    image: postgres:10
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: api_password
      POSTGRES_USER: api_user
      POSTGRES_DB: ratesdb
  prometheus:
    build: prometheus/.
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
  grafana:
    image: grafana/grafana:5.0.4
    depends_on:
      - prometheus
    ports: 
      - 3000:3000
  migration_container:
    image: microsoft/aspnetcore-build:2.0
    volumes:
      - ./api:/app
    depends_on:
      - db
    working_dir: /app
    entrypoint: /bin/bash
    command: startup.sh