version: '3'
services:
  api:
    build: api/.
    ports:
     - "8080:80"
    depends_on: 
     - db
  db:
    image: postgres
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: api_password
      POSTGRES_USER: api_user
      POSTGRES_DB: ratesdb