// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using rate_api.DataAccess.Models;
using System;

namespace rateapi.Migrations
{
    [DbContext(typeof(RatesContext))]
    partial class RatesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("rate_api.DataAccess.Models.Rate", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DayOfWeek");

                    b.Property<string>("EndTime");

                    b.Property<double>("Price");

                    b.Property<string>("StartTime");

                    b.HasKey("RateId");

                    b.ToTable("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
